/*
Function Study Examples
IS664 Fall 2022

*/

DROP DATABASE IF EXISTS widgetmaster;
CREATE DATABASE widgetmaster;
USE widgetmaster;

DELIMITER //
CREATE FUNCTION sum1DArray(A JSON)
RETURNS INT
DETERMINISTIC

BEGIN
	DECLARE S INT; DECLARE V INT; DECLARE I INT;
	SET S = 0; SET V = 0;
	SET I = 0; 
	WHILE I < JSON_LENGTH(A) DO
		SELECT JSON_EXTRACT(A,CONCAT('$[',I,']')) INTO V;
		SET S = S + V;
		SET I = I + 1;
	END WHILE;
	RETURN S;
END //
DELIMITER ;

SELECT sum1DArray(JSON_ARRAY(1,2,3)) AS 'sum1DArray';

DELIMITER //
CREATE FUNCTION averageArray(A JSON)
RETURNS DECIMAL(10,2)
DETERMINISTIC

BEGIN
	DECLARE I INT; DECLARE MU DECIMAL(10,2);
	SET I = 0; SET MU = 0;
	WHILE I < JSON_LENGTH(A) DO 
		SET MU = MU + JSON_EXTRACT(A,CONCAT('$[',I,']'));
		SET I = I + 1;
	END WHILE;
	SET MU = MU / JSON_LENGTH(A);
	RETURN MU;

END //
DELIMITER ;

SELECT averageArray(JSON_ARRAY(1,2,3,4,5,6,7)) AS 'averageArray';

DELIMITER //
CREATE FUNCTION varianceArray(A JSON)
RETURNS DECIMAL(10,2)
DETERMINISTIC

BEGIN
	DECLARE I INT; DECLARE MU DECIMAL(10,2); DECLARE SIGMA2 DECIMAL(10,2);
	DECLARE DIFF INT;
	SET I = 0; 
	SET MU = averageArray(A);
	SET DIFF = 0; SET SIGMA2 = 0;
	WHILE I < JSON_LENGTH(A) DO
		SET DIFF =  POW(MU - JSON_EXTRACT(A,CONCAT('$[',I,']')),2);
		SET SIGMA2 = SIGMA2 + DIFF;
		SET I = I + 1;
	END WHILE;
	SET SIGMA2 = SIGMA2 / JSON_LENGTH(A);
	RETURN SIGMA2;

END //
DELIMITER ;

SELECT varianceArray(JSON_ARRAY(1,2,3,4,5)) AS 'varianceArray';

DELIMITER //
CREATE FUNCTION stdDeviationArray(A JSON)
RETURNS DECIMAL(10,2)
DETERMINISTIC

BEGIN
	DECLARE SIGMA DECIMAL(10,2);
	SET SIGMA = SQRT(varianceArray(A));
	RETURN SIGMA;

END //
DELIMITER ;

SELECT stdDeviationArray(JSON_ARRAY(1,2,3,4,5)) AS 'stdDeviationArray';

DELIMITER //
CREATE FUNCTION countEvenOdds(A JSON)
RETURNS JSON
DETERMINISTIC

BEGIN
	DECLARE I INT; DECLARE OC INT; DECLARE EC INT;
	DECLARE RA JSON;
	SET RA = JSON_ARRAY();
	SET I = 0; SET OC = 0; SET EC = 0;
	WHILE I < JSON_LENGTH(A) DO
		IF JSON_EXTRACT(A,CONCAT('$[',I,']')) MOD 2 = 1 THEN
			SET OC = OC + 1;
		END IF;
		IF JSON_EXTRACT(A,CONCAT('$[',I,']')) MOD 2 = 0 THEN
			SET EC = EC + 1;
		END IF;
		SET I = I + 1;
	END WHILE;
	SET RA = JSON_ARRAY_INSERT(RA,'$[0]',OC);
	SET RA = JSON_ARRAY_INSERT(RA,'$[1]',EC);
	RETURN RA;

END //
DELIMITER ;

SELECT countEvenOdds(JSON_ARRAY(1,2,3,4,5,6,7)) AS 'CountEO';

DELIMITER //
CREATE FUNCTION sum2DArray(A JSON)
RETURNS INT
DETERMINISTIC

BEGIN
	DECLARE S INT; DECLARE V INT; DECLARE I INT; DECLARE J INT;
	SET S = 0; SET V = 0;
	SET I = 0; 
	WHILE I < JSON_LENGTH(A) DO
		SET J = 0;
		WHILE J < JSON_LENGTH(JSON_EXTRACT(A,CONCAT('$[',I,']'))) DO
			SELECT JSON_EXTRACT(A,CONCAT('$[',I,']','[',J,']')) INTO V;
			SET S = S + V;
			SET J = J + 1;
		END WHILE;		
		SET I = I + 1;
	END WHILE;
	RETURN S;
END //
DELIMITER ;

SET @A = JSON_ARRAY(JSON_ARRAY(1,1,1),JSON_ARRAY(2,2,1),JSON_ARRAY(3,1,1));
SELECT sum2DArray(@A) AS 'sum2DArray';

DELIMITER //
CREATE FUNCTION get2DColumn(A JSON, C INT)
RETURNS JSON
DETERMINISTIC

BEGIN
	DECLARE I INT; DECLARE J INT; DECLARE K INT; DECLARE IX INT;
	DECLARE RA JSON; DECLARE RS VARCHAR(100);
	SET RA = JSON_ARRAY(); 
	SET I = 0; SET IX = 0;
	WHILE I < JSON_LENGTH(A) DO
		SET J = 0;
		WHILE J < JSON_LENGTH(JSON_EXTRACT(A,CONCAT('$[',I,']','[',C,']'))) DO
			SET K = JSON_EXTRACT(A,CONCAT('$[',I,']','[',C,']'));
			SET RA = JSON_ARRAY_INSERT(RA,CONCAT('$[',IX,']'),K);
			SET J = J + 1;
			SET IX = IX + 1;
		END WHILE;
		SET I = I + 1;
	END WHILE;
	RETURN RA;

END //
DELIMITER ;

SELECT get2DColumn(@A,0) AS 'get2DColumn';

DELIMITER //
CREATE FUNCTION get2DRow(A JSON, R INT)
RETURNS JSON
DETERMINISTIC

BEGIN
	DECLARE I INT; DECLARE K JSON; DECLARE L INT;
	DECLARE GA JSON; DECLARE RA JSON;
	SET RA = JSON_ARRAY(); 
	SET I = 0;
	SET K = JSON_EXTRACT(A,CONCAT('$[',R,']'));
	SET GA = K;
	WHILE I < JSON_LENGTH(GA) DO
		SET L = JSON_EXTRACT(GA,CONCAT('$[',I,']'));
		SET RA = JSON_ARRAY_INSERT(RA,CONCAT('$[',I,']'),L);
		SET I = I + 1;
	END WHILE;
	RETURN GA;

END //
DELIMITER ;

SELECT get2DRow(@A,1) AS 'get2DRow';

DELIMITER //
CREATE FUNCTION get2DTrace(A JSON)
RETURNS INT
DETERMINISTIC

BEGIN
	DECLARE I INT; DECLARE J INT; DECLARE T INT;
	SET I = 0;SET T = 0;
	WHILE I < JSON_LENGTH(A) DO
			SET J = 0;
			WHILE J < JSON_LENGTH(JSON_EXTRACT(A,CONCAT('$[',I,']'))) DO
				IF I = J THEN
					SET T = T + JSON_EXTRACT(A,CONCAT('$[',I,']','[',J,']'));
				END IF;
				SET J  = J + 1;
			END WHILE;
		SET I = I + 1;
	END WHILE;
	RETURN T;

END //
DELIMITER ;

SELECT get2DTrace(@A) AS 'get2DTrace';

DELIMITER //
CREATE FUNCTION getObjectArray(O JSON,K VARCHAR(10))
RETURNS JSON
DETERMINISTIC

BEGIN
	DECLARE RA JSON;
	SET RA = JSON_EXTRACT(O,CONCAT('$.',K));
	RETURN RA;
END //
DELIMITER ;

SET @B = JSON_OBJECT('Alpha',JSON_ARRAY(1,2,3),'Beta',JSON_ARRAY(4,5,6));
SELECT getObjectArray(@B,'Alpha') AS 'getObjectArray';