/*
Homework Solution 2
IS664 Database Programming
User-Defined Functions
*/

USE imperial_defense;

DROP FUNCTION IF EXISTS calculateHours;
DELIMITER //
CREATE FUNCTION calculateHours(D1 DATE, D2 DATE)
RETURNS INT
DETERMINISTIC

BEGIN
	DECLARE HRS INT;
	DECLARE DYS INT;
	SET DYS = ABS(DATEDIFF(D1,D2));
	SET HRS = DYS * 24;
	RETURN HRS;


END //
DELIMITER ;

SELECT calculateHours('2020-01-03','2020-01-01' ) AS T1;

DROP FUNCTION IF EXISTS determineLargestTimeGap;
DELIMITER //
CREATE FUNCTION determineLargestTimeGap(D1 DATE, D2 DATE,D3 DATE, D4 DATE)
RETURNS VARCHAR(50)
DETERMINISTIC

BEGIN
	DECLARE G1 INT;
	DECLARE G2 INT;
	DECLARE RESULT VARCHAR(50);
	SET G1 = ABS(calculateHours(D1,D2));
	SET G2 = ABS(calculateHours(D3,D4));
	IF G1 > G2 THEN
		SET RESULT = CONCAT('GAP-',D1,'-TO-',D2);
	ELSE
		SET RESULT = CONCAT('GAP-',D3,'-TO-',D4);
	END IF;
	RETURN RESULT;


END //
DELIMITER ;

SELECT determineLargestTimeGap('2020-01-01','2020-03-01','2020-04-01','2020-011-01') AS T2;

DROP FUNCTION IF EXISTS sumString;
DELIMITER //
CREATE FUNCTION sumString(V VARCHAR(20))
RETURNS INT
DETERMINISTIC

BEGIN
	DECLARE I INT; DECLARE SLength INT;
	DECLARE S INT; DECLARE Num INT;

	SET I = 0; SET SLength = CHARACTER_LENGTH(V);
	SET S = 0;
	WHILE I < SLength DO
		SET Num = SUBSTRING(V,(I + 1),1);
		SET S = S + Num;		
		SET I = I + 1;		
	END WHILE;
	RETURN S;
END //
DELIMITER ;

-- SELECT sumString('12345') AS T3;

DROP FUNCTION IF EXISTS calcVariance;
DELIMITER //
CREATE FUNCTION calcVariance(V VARCHAR(10))
RETURNS DECIMAL(10,2)
DETERMINISTIC

BEGIN
	DECLARE Num INT; DECLARE MU DECIMAL(10,2); DECLARE SIGMA2 DECIMAL(10,2);
	DECLARE SLength INT; DECLARE I INT;

	SET SLength = CHARACTER_LENGTH(V);
	SET MU = sumString(V) / SLength;
	SET SIGMA2 = 0;
	SET I = 0;
	WHILE I < SLength DO
		SET Num = SUBSTRING(V,(I + 1),1);
		SET SIGMA2 = SIGMA2 +  POW((Num - MU),2);
		SET I = I + 1;		
	END WHILE;
	SET SIGMA2 = SIGMA2 / SLength;
	RETURN SIGMA2;

END //
DELIMITER ;

SELECT calcVariance('12345') AS T3;

DROP FUNCTION IF EXISTS calcStandardDeviation;
DELIMITER //
CREATE FUNCTION calcStandardDeviation(V VARCHAR(10))
RETURNS DECIMAL(10,2)
DETERMINISTIC

BEGIN
	DECLARE SIGMA DECIMAL(10,2);
	SET SIGMA = SQRT(calcVariance(V));
	RETURN SIGMA;

END //
DELIMITER ;

SELECT calcStandardDeviation('12345') AS T4;