USE asteroids;

DROP FUNCTION IF EXITS convertCountry;
DELIMITER;
CREATE FUNCTION convertCountry(D DATE)
RETURNS VARCHAR(10)
DETERMINISTIC

BEGIN //

END //

DROP PROCEDURE IF EXISTS showtypes;
DELIMITER //
CREATE PROCEDURE showType(T VARCHAR(20), C INT)

BEGIN
    DECLARE I INT; DECALRE R INT;
    DECALRE

    DECLARE X_CURSOR CURSOR FOUND_ROWS
    SELECT * FROM Registry WHERE Atype = T LIMIT C;

    SET I = 0;
    SET R = FOUND_ROWS();
    WHILE I < R DO
        SET I = I + 1;
    END WHILE;





END //
DELIMTER ;

CALL showType();


DROP PROCEDURE IF EXISTS showValues;
DELIMTER //
CREATE FUNCTION showValues(T VARCHAR(20), )


