
use imperial_defense; 


DROP PROCEDURE componentSummary;

DELIMITER //						
CREATE PROCEDURE componentSummary(N varchar(60))

BEGIN

	DECLARE COUNT_ROWS,I INT;

	DECLARE N_NAME /*,HID,SW_ID,RP_ID*/ VARCHAR(60);
	-- DECLARE HID VARCHAR(60); DECLARE SW_ID VARCHAR(60); DECLARE RP_ID VARCHAR(60); --
	/* DECLARE H_RANGE VARCHAR(60); DECLARE S_RANGE VARCHAR(60); DECLARE R_RANGE VARCHAR(60); */

	DECLARE NET_CURSOR CURSOR FOR SELECT NetName,HID,SID,RPID FROM NETWORK, HUB, SWITCH, REPEATER 
	where HUB.AssignedTo = NETWORK.NetName and SWITCH.AssignedTo = NETWORK.NetName and REPEATER.AssignedTo = NETWORK.NetName
	and Network.NetName = 'Brore06vNET_SURV' ;

	OPEN NET_CURSOR;
		SET COUNT_ROWS = FOUND_ROWS();
		SET I = 0;
		WHILE I < COUNT_ROWS DO
			FETCH NET_CURSOR INTO N_NAME /*, HID, SW_ID, RP_ID*/ ;
			SELECT CONCAT('This is ' , N_NAME/*, HID, SW_ID, RP_ID*/);
			SET I = I + 1;
		END WHILE;
	CLOSE NET_CURSOR;

END //

DELIMITER ;

CALL componentSummary('Brore06vNET_SURV');
