DROP DATABASE IF EXISTS LocklearDB;
CREATE DATABASE LocklearDB;
USE LocklearDB;

CREATE TABLE R1(
A VARCHAR(20),
B DECIMAL(10,2),
C INT,
D DECIMAL AS (B * C),
CONSTRAINT PK_R1 PRIMARY KEY(A)
);

INSERT INTO R1 (A,B,C) VALUES('PRANJAL',100.00,54);
INSERT INTO R1 (A,B,C) VALUES('GEORGE',200.00,45);

SELECT * FROM R1;