DROP DATABASE IF EXISTS LocklearDB;
CREATE DATABASE LocklearDB;
USE LocklearDB;

CREATE TABLE R1(
A VARCHAR(20),
B DECIMAL(10,2),
C INT,
CONSTRAINT PK_R1 PRIMARY KEY(A)
);

DESCRIBE R1;

INSERT INTO R1 (A,c) VALUES('PRANJAL', 27);
INSERT INTO R1 VALUES('PRANJOL', 200.00,45);

SELECT * FROM R1;