DROP DATABASE IF EXISTS LocklearDB;
CREATE DATABASE LocklearDB;
USE LocklearDB;

CREATE TABLE IF NOT EXISTS R1(
-- CREATE TABLE R1(
A VARCHAR(20) PRIMARY KEY,
B DECIMAL(10,2),
C INT
);

DESCRIBE R1;

CREATE TEMPORARY TABLE IF NOT EXISTS R2(
-- CREATE TABLE R2(
A VARCAHR(20) PRIMARY KEY,
B DECIMAL(10,2),
C INT
);

DESCRIBE R2;

CREATE TABLE IF NOT EXISTS R3 LIKE R1;

DESCRIBE R1;
CREATE TABLE R4 AS SELECT * FROM R1;
DESCRIBE R4;

DROP TABLE R2;
SELECT * FROM R2;

ALTER TABLE R1 DROP B;
DESCRIBE R1;

-- remove a relation or attribute