-- DROP DATABASE IF EXISTS LocklearDB;
CREATE DATABASE LocklearDB;
USE LocklearDB;

-- CREATE TABLE IF NOT EXISTS R1(
CREATE TABLE R1(
A VARCHAR(20) PRIMARY KEY,
B DECIMAL(10,2),
C INT
);

DESCRIBE R1;

-- CREATE TEMPORARY TABLE IF EXISTS R2(
CREATE TABLE R2(
A VARCAHR(20) PRIMARY KEY,
B DECIMAL(10,2),
C INT
);

DESCRIBE R2;