USE IMPERIAL_DEFENSE;

DELIMITER //
CREATE FUNCTION displayAuthorName()
RETURNS VARCHAR(30)
DETERMINISTIC

BEGIN
    DECLARE MyName VARCHAR(30);
    SET MyName = "Pranjal Shukla";
    RETURN MyName;

END //
DELIMITER ;

DROP TABLE IF EXISTS R_WIDGET;
DROP PROCEDURE IF EXISTS WIDGET_REFACTOR;
DELIMITER //
CREATE PROCEDURE WIDGET_REFACTOR()

  Declaring variablesBEGIN  DECLARE W_WID VARCHAR(20);  DECLARE W_TYPE VARCHAR(20);  DECLARE W_ASSIGNEDTO VARCHAR(40);
  DECLARE W_LOCATION VARCHAR(20);  DECLARE W_ACCESS VARCHAR(20);  DECLARE W_SECURE INT;
  DECLARE COUNTER INT;  DECLARE SUFFIX VARCHAR(20);  DECLARE R_ACCESS VARCHAR(20);  DECLARE R_SECURE VARCHAR(20);
  DECLARE XCO INT;  DECLARE YCO INT; DECLARE R_LOC VARCHAR(50);  DECLARE R_TYPE VARCHAR(20);
  DECLARE JSON_ENC VARCHAR(20);

  DECLARE C_WIDGET
  CURSOR FOR SELECT WID, WTYPE, ASSIGNEDTO, LOCATION, ACCESSCODE, SECURE FROM WIDGET LIMIT 10;
  CREATE TABLE R_WIDGET(
  RWID INT AUTO_INCREMENT PRIMARY KEY,
  WIDGETID VARCHAR(20) UNIQUE,
  RTYPE ENUM('IDEV','IPAD','ITERM'),
  NETASSIGNED VARCHAR(40),
  RNETTYPE ENUM('SAT','TRACK','SURV','DEF','CIV'),
  RLOCATION VARCHAR(100),
  RACCESS ENUM('A1','B2','C3','D4'),
  RSECURE ENUM('ENCRYPTED','PLAINTEXT'),
  RUSER JSON
  );

  OPEN C_WIDGET;
    SET COUNTER = 0;
    WHILE COUNTER < 10 DO
    FETCH C_WIDGET INTO W_WID, W_TYPE, W_ASSIGNEDTO, W_LOCATION, W_ACCESS, W_SECURE;
      SELECT XCOORD, YCOORD FROM SITE WHERE SITENAME = W_LOCATION INTO XCO, YCO;
      SET R_LOC = CONCAT(W_LOCATION,'--X:',XCO,' Y:',YCO);

      #Modifying the values based on given condition
      IF W_TYPE = 'DEVICE' THEN     SET R_TYPE = 'IDEV';
        ELSEIF W_TYPE = 'PAD' THEN
        SET R_TYPE = 'IPAD';
          ELSE
        SET R_TYPE = 'ITERM';
        END IF;
        IF W_ASSIGNEDTO LIKE '%_SAT' THEN
          SET SUFFIX = 'SAT';
        ELSEIF W_ASSIGNEDTO LIKE '%_DEF' THEN
          SET SUFFIX = 'DEF';
        ELSEIF W_ASSIGNEDTO LIKE '%_CIV' THEN
          SET SUFFIX = 'CIV';
        ELSEIF W_ASSIGNEDTO LIKE '%_SURV' THEN
          SET SUFFIX = 'SURV';
        ELSEIF W_ASSIGNEDTO LIKE '%_TRACK' THEN
          SET SUFFIX = 'TRACK';
        ELSE
          SET SUFFIX = 'NONE OF THE VALUES MATCH';
        END IF;
        IF W_ACCESS LIKE 'A%' THEN
          SET R_ACCESS = 'A1';
        ELSEIF W_ACCESS LIKE 'B%' THEN
          SET R_ACCESS = 'B2';
        ELSEIF W_ACCESS LIKE 'C%' THEN
          SET R_ACCESS = 'C3';
        ELSE
          SET R_ACCESS = 'D4';
        END IF;
          IF W_SECURE = 0 THEN
        SET R_SECURE = 'PLAINTEXT';
          ELSE
        SET R_SECURE = 'ENCRYPTED';
        END IF;
        IF R_SECURE = 'PLAINTEXT' THEN
          SET JSON_ENC = 'USER NOT ENCRYPTED';
        ELSE
          SET JSON_ENC = 'USER ENCRYPTED';
        END IF;

        INSERT INTO R_WIDGET (WIDGETID, RTYPE, NETASSIGNED, RNETTYPE, RLOCATION, RACCESS, RSECURE, RUSER)
        VALUES (W_WID, R_TYPE, W_ASSIGNEDTO, SUFFIX, R_LOC, R_ACCESS, R_SECURE,JSON_OBJECT("ID",W_WID,"DEVICE:",W_TYPE,"ACCESS CODE",W_ACCESS,"ENCRYPTED_YN",JSON_ENC));
        SET COUNTER = COUNTER + 1;  END WHILE;  CLOSE C_WIDGET;

SELECT * FROM R_WIDGET;

END //
DELIMITER ;
CALL WIDGET_REFACTOR();
