DROP DATABASE IF EXISTS PACEML;
CREATE DATABASE PACEML;
USE PACEML;

-- CREATE A FUNCTION TO CALCULATE MINIMUM VALUE 
DROP FUNCTION IF EXISTS MINVALUE;
DELIMITER //
CREATE FUNCTION MINVALUE(JA JSON)
RETURNS INT
DETERMINISTIC

BEGIN
   DECLARE MIN_VAL INT;
   DECLARE I INT; DECLARE TEMP INT ; DECLARE A INT;
   
   SET I = 0;
   SET TEMP = 0;

    WHILE I < JSON_LENGTH(JA) DO 
     
    SET A = JSON_EXTRACT( JA,CONCAT('$[',I,']') ) ;

     IF  I = 0 THEN 
      IF TEMP < A THEN 
         SET TEMP = A ;
          SET MIN_VAL = TEMP;
      END IF ;
     ELSE     
        IF TEMP < A THEN 
           SET MIN_VAL = TEMP;
        END IF ;
        IF TEMP > A THEN 
          SET TEMP = A;
          SET MIN_VAL = TEMP;
        END IF ;
     END IF ; 
    SET I = I + 1;
   END WHILE;
  
   RETURN MIN_VAL;
END //
DELIMITER ;
