

USE IMPERIAL_DEFENSE;


-- FUNCTION TO CONCATENATE THE FWCODE 
DROP FUNCTION IF EXISTS GET_DATA;

DELIMITER //
CREATE FUNCTION GET_DATA(N_ID VARCHAR(20), N_SYSNM VARCHAR(20), N_FILTR VARCHAR(20))
RETURNS VARCHAR(60)
DETERMINISTIC

BEGIN
DECLARE FW_CODE VARCHAR(60) ;

-- GET FIRST 3 CHARACTERS FROM STRING 
    SET FW_CODE = SUBSTRING(N_ID,1,3); 

   IF FW_CODE = 'FW_' THEN
      SET FW_CODE = 'FW_101_';
    END IF;
    
    IF FW_CODE = 'FWX' THEN    
        SET FW_CODE = 'FWX001_101_';
    END IF;
    
    IF FW_CODE ='FW-' THEN
        SET FW_CODE = 'FW-111_101_';
    END IF;
    

   SET FW_CODE = CONCAT(FW_CODE,'88');
   SET FW_CODE = CONCAT(FW_CODE,N_SYSNM);
   SET FW_CODE = CONCAT(FW_CODE,'_');

    IF N_FILTR = 'PACKET' THEN
        SET FW_CODE = CONCAT(FW_CODE,'PKT');      
    END IF ;

    IF N_FILTR = 'FRAME' THEN
        SET FW_CODE = CONCAT(FW_CODE,'FRM');
    END IF; 

    RETURN FW_CODE;
END //
DELIMITER ;
   

-- Procedure to update the firewall code table 
DROP PROCEDURE IF EXISTS FIREWALLACCESSCODES;
DELIMITER //



CREATE PROCEDURE FIREWALLACCESSCODES( )
BEGIN
 -- DECLARATION OF  VARIABLES 
 DECLARE COUNT INT;
 DECLARE COUNTER INT;
 DECLARE N_ID VARCHAR(20);
 DECLARE N_SYSNM VARCHAR(20);
 DECLARE N_FILTR VARCHAR(20);
 DECLARE FW_CODE VARCHAR(60);

Begin
-- Declare Cursor 
DECLARE TAB_CURSOR CURSOR FOR  SELECT IDNUMBER, SYSTEMNAME, FILTER FROM FIREWALLcodes;

-- Open cursor 
OPEN TAB_CURSOR;
-- get the no. of rows in the table 
         SET COUNT = FOUND_ROWS(); 
         SET COUNTER = 0;

         WHILE COUNTER < COUNT DO
-- Fetch Cursor 
         FETCH TAB_CURSOR INTO N_ID, N_SYSNM, N_FILTR ;
   
         SET FW_CODE = GET_DATA(N_ID, N_SYSNM,N_FILTR);
-- Update the table 
         UPDATE FIREWALLCODES SET FWCODE = FW_CODE  WHERE IDNUMBER = N_ID  ;
         SET COUNTER = COUNTER + 1;
         END WHILE; 
CLOSE TAB_CURSOR;
END //
DELIMITER ;

 -- TABLE CREATION 
DROP TABLE IF EXISTS FIREWALLCODES ;   
   
CREATE TABLE FIREWALLCODES(
    FID INT AUTO_INCREMENT PRIMARY KEY ,
    IDNUMBER VARCHAR(20) UNIQUE KEY,
    SYSTEMNAME VARCHAR(20),
    FILTER ENUM('PACKET','FRAME'),
    FWCODE VARCHAR(60)
    );
                            
 -- DEFAULT FID                         
    ALTER TABLE FIREWALLCODES AUTO_INCREMENT = 76 ;
    
INSERT INTO FIREWALLCODES ( IDNUMBER,SYSTEMNAME, FILTER)
SELECT IDNUMBER,SYSTEMNAME,FILTER FROM FIREWALL;

-- call procedure 
CALL FIREWALLACCESSCODES();

/*
-- Procedute to display network summary
DROP PROCEDURE IF EXISTS componentSummary;
DELIMITER //
CREATE PROCEDURE componentSummary(P_netname VARCHAR())
Begin

-- declare cursor

-- open cursor 
-- fetch cursor 
-- close cursor 

CLOSE TAB_CURSOR;
END //
DELIMITER ;*/