/*
SCRIPT - STORED PROCEDURE USING CURSORS   
 - BY LEENA BHIRUD
24 OCTOBER 2021
*/

USE IMPERIAL_DEFENSE;


-- FUNCTION TO CONCATENATE THE FWCODE 
DROP FUNCTION IF EXISTS GET_DATA;

DELIMITER //
CREATE FUNCTION GET_DATA( N_ID VARCHAR(20), N_SYSNM VARCHAR(20), N_FILTR VARCHAR(20) )
RETURNS VARCHAR(60)
DETERMINISTIC

BEGIN
DECLARE FW_CODE VARCHAR(60) ;

-- GET FIRST 3 CHARACTERS FROM STRING 
    SET FW_CODE = SUBSTRING(N_ID,1,3); 

   IF FW_CODE = 'FW_' THEN
      SET FW_CODE = 'FW_101_';
    END IF;
    
    IF FW_CODE = 'FWX' THEN    
        SET FW_CODE = 'FWX001_101_';
    END IF;
    
    IF FW_CODE ='FW-' THEN
        SET FW_CODE = 'FW-111_101_';
    END IF;
    

   SET FW_CODE = CONCAT(FW_CODE,'88');
   SET FW_CODE = CONCAT(FW_CODE,N_SYSNM);
   SET FW_CODE = CONCAT(FW_CODE,'_');

    IF N_FILTR = 'PACKET' THEN
        SET FW_CODE = CONCAT(FW_CODE,'PKT');      
    END IF ;

    IF N_FILTR = 'FRAME' THEN
        SET FW_CODE = CONCAT(FW_CODE,'FRM');
    END IF; 

    RETURN FW_CODE;
END //
DELIMITER ;
   


-- PROCEDURE TO UPDATE THE FIREWALL CODE TABLE 
DROP PROCEDURE IF EXISTS FIREWALLACCESSCODES;
DELIMITER //
 -- TABLE CREATION 
DROP TABLE IF EXISTS FIREWALLCODES ;   
   
CREATE TABLE FIREWALLCODES(
    FID INT AUTO_INCREMENT PRIMARY KEY ,
    IDNUMBER VARCHAR(20) UNIQUE KEY,
    SYSTEMNAME VARCHAR(20),
    FILTER ENUM('PACKET','FRAME'),
    FWCODE VARCHAR(60)
    );
                            
 -- DEFAULT FID                         
    ALTER TABLE FIREWALLCODES AUTO_INCREMENT = 76 ;
    
INSERT INTO FIREWALLCODES ( IDNUMBER,SYSTEMNAME, FILTER)
SELECT IDNUMBER,SYSTEMNAME,FILTER FROM FIREWALL; 

CREATE PROCEDURE FIREWALLACCESSCODES( ) 

BEGIN
 -- DECLARATION OF  VARIABLES 
 DECLARE COUNT INT;
 DECLARE COUNTER INT;
 DECLARE N_ID VARCHAR(20);
 DECLARE N_SYSNM VARCHAR(20);
 DECLARE N_FILTR VARCHAR(20);
 DECLARE FW_CODE VARCHAR(60);


-- DECLARE CURSOR 
DECLARE TAB_CURSOR CURSOR FOR  SELECT IDNUMBER, SYSTEMNAME, FILTER FROM FIREWALLCODES;

-- OPEN CURSOR 
OPEN TAB_CURSOR;
-- GET THE NO. OF ROWS IN THE TABLE 
         SET COUNT = FOUND_ROWS(); 
         SET COUNTER = 0;

         WHILE COUNTER < COUNT DO
-- FETCH CURSOR 
         FETCH TAB_CURSOR INTO N_ID, N_SYSNM, N_FILTR ;
   
         SET FW_CODE = GET_DATA(N_ID, N_SYSNM,N_FILTR);
-- UPDATE THE TABLE 
         UPDATE FIREWALLCODES SET FWCODE = FW_CODE  WHERE IDNUMBER = N_ID  ;
         SET COUNTER = COUNTER + 1;
         END WHILE; 
-- CLOSE CURSOR
CLOSE TAB_CURSOR;
-- DISPLAY TABLE 
 SELECT * FROM FIREWALLCODES ;

END //
DELIMITER ;

 -- CALL PROCEDURE 
CALL FIREWALLACCESSCODES();



DROP PROCEDURE COMPONENTSUMMARY;
DELIMITER //
CREATE PROCEDURE COMPONENTSUMMARY(P_NETNAME VARCHAR(20))

BEGIN
-- CREATE VARIABLES
   DECLARE  R_COUNTER INT ;
   DECLARE  R_COUNT INT  ;
   DECLARE MSG VARCHAR(600);
   DECLARE N_ID VARCHAR(20); DECLARE N_NAME VARCHAR(20); DECLARE N_HID VARCHAR(20); DECLARE N_HRANGE VARCHAR(20);
   DECLARE N_SID VARCHAR(20); DECLARE N_SRANGE VARCHAR(20); DECLARE N_RPID VARCHAR(20);DECLARE N_RRANGE VARCHAR(20);
  


-- DECLARE CURSOR

DECLARE NW_CURSOR CURSOR FOR SELECT N.NETNAME,H.HID, ABS(H.ENTRYPORT - H.EXITPORT) AS HUBRANGE, 
                                    S.SID, ABS(S.ENTRYPORT - S.EXITPORT) AS SWITCHRANGE, 
                                    R.RPID, ABS(R.ENTRYPORT - R.EXITPORT) AS REPEATER_PORT
                                    FROM NETWORK N INNER JOIN HUB H 
                                    ON N.NETNAME = H.ASSIGNEDTO
                                    INNER JOIN SWITCH S
                                    ON N.NETNAME = S.ASSIGNEDTO 
                                    INNER JOIN REPEATER R
                                    ON N.NETNAME = R.ASSIGNEDTO
                                    WHERE N.NETNAME = P_NETNAME ORDER BY S.SID, R.RPID;


-- OPEN CURSOR                                   
OPEN NW_CURSOR;
     SET R_COUNT = FOUND_ROWS();
     SET R_COUNTER = 0;
-- FETCH CURSOR   
   WHILE R_COUNTER < R_COUNT DO
   FETCH NW_CURSOR INTO N_NAME, N_HID, N_HRANGE, N_SID, N_SRANGE, N_RPID, N_RRANGE;
      SET MSG = CONCAT('HUB:',N_HID, '  SWITCH: ', N_SID, ' REPEATER: ', N_RRANGE,'\n');
      SET MSG = CONCAT(MSG,'HUB PORT RANGE: HUB HAS RANGE OF ',N_HRANGE,'\n','SWITCH PORT RANGE: SWITCH HAS RANGE OF ',N_SRANGE,'\n',
                       'REPEATER PORT RANGE: SWITCH HAS RANGE OF ',N_RRANGE,'\n',
                        'ALL COMPONENTS ASSIGNED TO: ', N_NAME);
-- DISPLAY DATA       
      SELECT MSG AS 'MSG';
      SET R_COUNTER = R_COUNTER + 1;
   END WHILE;

CLOSE NW_CURSOR;

END //
DELIMITER ;

CALL COMPONENTSUMMARY('BRORE01WNET_TRACK');
